const fs = require("fs"); // No installation needed for this!

class ReportService {
    async generateFinalReport() {
        const data = {
            group: "Digital Njangi Platform",
            balance: "150,000 XAF",
            status: "Week 3 Confirmed"
        };

        // This is the layout of your physical report
        const reportText = `
        ====================================
        OFFICIAL NJANGI DIGITAL LEDGER
        ====================================
        Group Name:    ${data.group}
        Total Balance: ${data.balance}
        Status:        ${data.status}
        Date:          ${new Date().toLocaleString()}
        ====================================
        Generated by Glory's Njangi System
        `;

        // This command creates the actual file on your laptop
        fs.writeFileSync("Njangi_Final_Report.txt", reportText);

        console.log("------------------------------------");
        console.table(data);
        console.log("✅ SUCCESS: File created -> Njangi_Final_Report.txt");
        console.log("------------------------------------");
    }
}

const reporter = new ReportService();
reporter.generateFinalReport();