'use strict';

const PDFDocument = require('pdfkit');

/**
 * PDFService — generate financial reports and receipts using PDFKit.
 * Returns a Buffer — caller handles upload to Supabase Storage.
 *
 * Uses PDFKit (not Puppeteer) — lightweight, no browser dependency.
 *
 * @task Dev C — Task C-06
 */
class PDFService {
  /**
   * Generate a full group financial report.
   * @param {{ name: string }} groupData
   * @param {{ totalContributed, totalPaidOut, balance, cycles: Array }} ledgerData
   * @returns {Promise<Buffer>}
   */
  generateLedgerReport(groupData, ledgerData) {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));

    // Header
    doc.fontSize(20).font('Helvetica-Bold')
      .text('NjangiBridge — Financial Report', { align: 'center' });
    doc.fontSize(12).font('Helvetica')
      .text(`Group: ${groupData.name}`, { align: 'center' });
    doc.text(`Generated: ${new Date().toLocaleDateString('en-CM')}`, { align: 'center' });
    doc.moveDown();

    // Summary section
    doc.fontSize(14).font('Helvetica-Bold').text('Summary');
    doc.fontSize(10).font('Helvetica');
    doc.text(`Total Contributed: ${ledgerData.totalContributed?.toLocaleString()} FCFA`);
    doc.text(`Total Paid Out:    ${ledgerData.totalPaidOut?.toLocaleString()} FCFA`);
    doc.text(`Current Balance:   ${ledgerData.balance?.toLocaleString()} FCFA`);
    doc.moveDown();

    // Per-cycle detail
    for (const cycle of (ledgerData.cycles || [])) {
      doc.addPage();
      doc.fontSize(14).font('Helvetica-Bold').text(`Cycle ${cycle.cycleNumber}`);
      doc.fontSize(9).font('Helvetica');

      // Table header
      doc.text('Member', 50, doc.y, { width: 180, continued: true });
      doc.text('Amount (FCFA)', { width: 120, continued: true });
      doc.text('Status', { width: 80, continued: true });
      doc.text('Date');
      doc.moveDown(0.5);

      // Rows
      for (const c of (cycle.contributions || [])) {
        doc.text(c.memberName || '—', 50, doc.y, { width: 180, continued: true });
        doc.text(String(c.amount), { width: 120, continued: true });
        doc.text(c.status, { width: 80, continued: true });
        doc.text(c.date ? new Date(c.date).toLocaleDateString() : '—');
      }

      if (cycle.payout) {
        doc.moveDown();
        doc.font('Helvetica-Bold')
          .text(`Payout → ${cycle.payout.recipientName}: ${cycle.payout.amount?.toLocaleString()} FCFA`);
      }
    }

    doc.end();

    return new Promise((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });
  }

  /**
   * Generate a single-page payment receipt.
   * @param {{ memberName, amount, method, date, groupName, cycleNumber }} contribution
   * @returns {Promise<Buffer>}
   */
  generateReceiptPDF(contribution) {
    const doc = new PDFDocument({ margin: 50, size: 'A5' });
    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));

    doc.fontSize(18).font('Helvetica-Bold')
      .text('NjangiBridge — Payment Receipt', { align: 'center' });
    doc.moveDown();
    doc.fontSize(11).font('Helvetica');
    doc.text(`Member:       ${contribution.memberName}`);
    doc.text(`Group:        ${contribution.groupName}`);
    doc.text(`Cycle:        ${contribution.cycleNumber}`);
    doc.text(`Amount:       ${contribution.amount?.toLocaleString()} FCFA`);
    doc.text(`Method:       ${contribution.method}`);
    doc.text(`Date:         ${new Date(contribution.date).toLocaleDateString('en-CM')}`);
    doc.moveDown();
    doc.fontSize(9).fillColor('grey')
      .text('This receipt is auto-generated by NjangiBridge. Keep for your records.');

    doc.end();

    return new Promise((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });
  }
}

module.exports = new PDFService();
